sprite $symplr_DAM [64x64/16z] {
xTG7ZkGW44RX1mKKuR__TJTr8vkMncjcS_WKxT9pDdoh__wBnJVamAfgKtxDMxdF-te0an9RN0hdhGe6M80OkQ6VpzYKoIf4THWAV5rLEVU9s0ngXkBSuAen
dFjDBaaz7TU_tm_fUHD3cm8k9xXax-d7euUg-kxhTy0qJizllu_IxzC7hpL1hgi2LgTqqIT97OPUGDFKBtfIpX5YNXc4FCKV_VmiFoKWvLNuChUhNfeAfXVr
CGyNVMbFDK9jA_ioznzr_o44WB1OTrtr9gb1rsf0rTGk-ZWaXwfLWwB9V-V_fpyqo7royFvPFEPlFxy7S4rzFj1qpD_eYVP506oQ6_4q_r7FpzqDagyoc3z4
oEvvV_suz__aKY9OMIM8vI52AYLzd_ilHrzLsDIKZpvh1BQO58-Uhf4jtcOkLKvzwDhKEFUGsv0qRcg9ev-I6djU-yucqu0fI94zLPL3qp1s5EaSX26DVfya
vonKRHcP5y7IVP6_m7yV0G
}

!define SYMPLR_DAM(_color)                                 SPRITE_PUT(                              symplr_DAM, _color)
!define SYMPLR_DAM(_color, _scale)                         SPRITE_PUT(                              symplr_DAM, _color, _scale)
!define SYMPLR_DAM(_color, _scale, _alias)                 SPRITE_ENT(  _alias, SYMPLR DAM,         symplr_DAM, _color, _scale)
!define SYMPLR_DAM(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, SYMPLR DAM,         symplr_DAM, _color, _scale, _shape)
!define SYMPLR_DAM(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, SYMPLR DAM, _label, symplr_DAM, _color, _scale, _shape)
skinparam folderBackgroundColor<<SYMPLR DAM>> White
