sprite $symplr_EUM [64x64/16z] {
rTO5ZiOw40DWXoO3llzvttQpqAZSnv_WHnSobHMSIoNXlUmaDU6b57GDEbxgx02C3Uy44u12_PVoIlbJrvz9wyx0MoL8UiPxfHQybDgFcl1OvKgK5slNspTb
uA5EcIPP7y--86KiKa9ZmnDPbhm75k5ex99mLrBIM134We568_lzbO-cdFCYTwUWf016wsHVaDqeIEE7ApPEuvpfkB1-7VU43xdLygksyMMmurGVyICvpWVP
60bd2dcqYBaa10lEDQgwjOEghWLNEXU6MIPTWuOhcMofE0NRgalEYWlocSmCJCZnv7LSqB52vAFyzloEoIXfkxx-J4gkGS6aZAfsN6hRzL_K86a9rxAwLMoL
cl-AgiOP2GxJnGfN8fzMWtyBHlfPErbLjUD8NYBp8xSjPsF1WVdnoBJlH4PEuxi4OJtE2zheX-Ppdeu5xIglB1YPEH_BkqJ_U_EQZIr_SDRwdNUQahfWgBFX
W70M-1ISTHoeOMgkfgfcgg7uL5hPLlMGHILXsCnj8rdTk-2wgQgZFEVshgIKJgRvz84ZIiNAg1DXtpJDWHJJnGQtzojq7AjanWzd7bEVUYhZX33I-bm99LZM
yOfJVLq0peLE2ueBkZw51Bsjnzbk5QmcR6KZwzrTim1Y_iqgKd-ma-wa6DUwC0It9MdhivLWQGbFTDPfhEt5_hK95gsXlSXF-yV_NTutfVQCaK76Weoh_7j_
}

!define SYMPLR_EUM(_color)                                 SPRITE_PUT(                              symplr_EUM, _color)
!define SYMPLR_EUM(_color, _scale)                         SPRITE_PUT(                              symplr_EUM, _color, _scale)
!define SYMPLR_EUM(_color, _scale, _alias)                 SPRITE_ENT(  _alias, SYMPLR EUM,         symplr_EUM, _color, _scale)
!define SYMPLR_EUM(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, SYMPLR EUM,         symplr_EUM, _color, _scale, _shape)
!define SYMPLR_EUM(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, SYMPLR EUM, _label, symplr_EUM, _color, _scale, _shape)
skinparam folderBackgroundColor<<SYMPLR EUM>> White
