sprite $symplr_Orchestration2 [64x64/16z] {
xTO73kmg38NX0yOOssV_wtteZIQAXank9hUNJq8j_EaDluj_2hv63T9mMqdorWg40-Om9eJ4nvI9O1aCb3iz14119JqOkAsJp8hxghPR6GsBxzTNP_QllKqw
xb96KJB-rp4LRzXKyuupdGE5VCZd_RVbd08dXBHWjaaVFQJWoUcQL9mOssrIcNYHhEWSE2DT2m0H9KMcthOT20wDAsUt9lTqExef2xveC2Fdc9BJjdD9lv33
sR0fv6w1uZlrOYRl-l6KR_lEIO_xlOP3XRH1waDGzulOTODZZG6G6rkE_voGqaX_IEfXNnxZY7EoDyVlG2HW50Wx3bbcVtl-0Gz0iwActhZ-Y-_TUmmpTpCB
_xnNSc_WKs9klPEZ3wRYfcH5e-Cdz4BziRqEgsVxlqvSR_zseNTEikukTP10LQ0se8pwx5Dt1Zb777stG0gSWc35O3px5uV_GOtPEWc80Qq3DTgZXuszO8en
yIeuwNhyroO2nS8RBlJBnCNIhxvdBzRhsgifBkcSsciV9ADSoEl-Eq8AK2jWp9wq2tsZ0zmuG0B9ZiQuSlJC_NUa0TO1fzV1WGk2awr7DGakA2EpuvK4G_3D
_VCV
}

!define SYMPLR_ORCHESTRATION2(_color)                                 SPRITE_PUT(                                         symplr_Orchestration2, _color)
!define SYMPLR_ORCHESTRATION2(_color, _scale)                         SPRITE_PUT(                                         symplr_Orchestration2, _color, _scale)
!define SYMPLR_ORCHESTRATION2(_color, _scale, _alias)                 SPRITE_ENT(  _alias, SYMPLR ORCHESTRATION2,         symplr_Orchestration2, _color, _scale)
!define SYMPLR_ORCHESTRATION2(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, SYMPLR ORCHESTRATION2,         symplr_Orchestration2, _color, _scale, _shape)
!define SYMPLR_ORCHESTRATION2(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, SYMPLR ORCHESTRATION2, _label, symplr_Orchestration2, _color, _scale, _shape)
skinparam folderBackgroundColor<<SYMPLR ORCHESTRATION2>> White
