sprite $symplr_UCS [64x64/16z] {
xT45OYGn34JHacp9LFU_xcv0eM6tm-at3BzD-3YxGeKKmLPEXT61XEqCC1Qia9O0mP9AnGhhWbKPSoGdnGkdOKhZdPeHj2gcfDPvfsTifpx8Yj0QvZaPcuyn
i44QR5YXPC6AH6fSgU02yHOAW5nBmgCQAz3XE4y7dobG-RnpGYgkwkmM4W2nGWw92JYk8WLlIO_3DtRSqsuuHyXJMo_n6ZlfKpqwSymj_eIvlj8ErZRNIwmt
PKpsXxwc5rlh2ssfhtJSQE_tVk_tVk-pcItqmZkslOVNMkNJrmzISAZHSAlEbWyugRXLuWcEsqdj1sh6R_OV
}

!define SYMPLR_UCS(_color)                                 SPRITE_PUT(                              symplr_UCS, _color)
!define SYMPLR_UCS(_color, _scale)                         SPRITE_PUT(                              symplr_UCS, _color, _scale)
!define SYMPLR_UCS(_color, _scale, _alias)                 SPRITE_ENT(  _alias, SYMPLR UCS,         symplr_UCS, _color, _scale)
!define SYMPLR_UCS(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, SYMPLR UCS,         symplr_UCS, _color, _scale, _shape)
!define SYMPLR_UCS(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, SYMPLR UCS, _label, symplr_UCS, _color, _scale, _shape)
skinparam folderBackgroundColor<<SYMPLR UCS>> White
