sprite $symplr_APIGateway [64x64/16z] {
pPM7bkig300HHKOm__-zRzc54-C7gRVDgP4oAIgM-uVnQgMO-lTioNIolA47m588oQ26TtJp_MyOX1TrgUJRgqoLr_o3uauKZjTy29T_yv8UgNEWlbO19S-1
ZBxszuzDO8lCRzSvgxClLpjMq6TzXHgdjASHd_CZ3J-dhTTixq-rDFHp__FVFyLUgHznEp4-brAfvKGFPB-VfZJym1t2yDFMDtACKUEP7Z3iiL_nReEdtl6B
geO7FlfDMVcDUjUF3Fxloz68Zxx_w8ZRyEZ_hn2_zRsVrZgTKpAYKEFIbm95rhMeS8pALGZIEVi5e9mi6GIelOf6SeKRDrz01EJs-aHn2VlnLUgK60XuV_8z
9wfJR7HrSryCm5RrbtfRU8KIt0enC9dzJYYWgyVfOUu4RFil3-Pdus-GR3_mm4_sHPRL_dJ2NR_GMErl-eRT_7RVfvJAfy-FVyzNRCoSnHFUEOaTkxr75-K_
bizlv-pQcdnjG9VIk1ytcX_x-HZt8wtkRnxhE0FpFHiBdxdUNydav_pC8PS9aElWHTBM3pHaBa2XnldURdqNAsNNvBt_cC_zc7FS-ps_Hm5qx_Vy5b25_4Mv
-gL5V_9RNLgEpiNljCYzssa6cXhI0hxFgQI6qlBLROa0yJ8fOP7VuLNdMrmBTPD_Z8p_-owG5DxMHx_V9vabzq_p7m
}

!define SYMPLR_APIGATEWAY(_color)                                 SPRITE_PUT(                                     symplr_APIGateway, _color)
!define SYMPLR_APIGATEWAY(_color, _scale)                         SPRITE_PUT(                                     symplr_APIGateway, _color, _scale)
!define SYMPLR_APIGATEWAY(_color, _scale, _alias)                 SPRITE_ENT(  _alias, SYMPLR APIGATEWAY,         symplr_APIGateway, _color, _scale)
!define SYMPLR_APIGATEWAY(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, SYMPLR APIGATEWAY,         symplr_APIGateway, _color, _scale, _shape)
!define SYMPLR_APIGATEWAY(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, SYMPLR APIGATEWAY, _label, symplr_APIGateway, _color, _scale, _shape)
skinparam folderBackgroundColor<<SYMPLR APIGATEWAY>> White
