sprite $symplr_BEE [64x64/16z] {
jTS7hkCw34RXd-eYp_xN-oO5Gk29b7ctVAX9V0o1Tbpq-zBmOVeo2o3qPOscJjLNTR8AJL-LYHaaBQaMRTY8cNNHWAgb0hwPPn2GTD4UkPMRIjHErpk5haBu
pTHIkI_OUPWIlkch4a_vsWVjZuwdoj0x1YCU6xStVUYc0wJDh0EQphrARwQT96drgTHQIsghtyfzvClC-sGPTkuBG9KMSu3mCQPpq-tK1pa5MYeGDUaXDOUe
XnwN9cig4xpgLN5Wtqzwnr_MtdJL0EsaWCXwSCZlP-JQYhNwkJix4enz7sjqvFrHAfzwWwQTJjY7lkFQ2zgvDyZQgyIkn-zmdSHk0eEdgfF6q0caJnTJ7IH2
Ps2wiB96Ld2T-PflBhR-QtFDT-XiKdGtdxCoeavwlkjyxljpora3UrnpZMNgBE397jV5pBIAzxk9V-ndlt6gpVii9goX9lZ7-HjhiNLq-__7t_gexyRJTF9f
mFMhvtyP3r2EksVS5LquJyS5n7OZn-vIdAy_oMxUzQUBtFNIUEWrTfUW35sVUqqeczdfr2yJkguw36tx0SDUjusgLpLUzcaJndMmmT1IW6ZhIj7NxUrk4a7N
2q9ofALpvtFEuAP92tvzc8Y_-rn6y12ZxVlh-bSloN94oIPbkhICjVwbhozMlnQcQwz1TEsT-y--tbj9vpuLqru3ngaVnnja8fhJqX_Zse_qHyDRaBHH_txy
NlrJkc-qKHXgUBzfUktL-etJD2ZQSI1CMZhqwwkSQw_DVialE-YpwTyHKg0lmoL7NpPmP-ZBRC8qwUliK_qV
}

!define SYMPLR_BEE(_color)                                 SPRITE_PUT(                              symplr_BEE, _color)
!define SYMPLR_BEE(_color, _scale)                         SPRITE_PUT(                              symplr_BEE, _color, _scale)
!define SYMPLR_BEE(_color, _scale, _alias)                 SPRITE_ENT(  _alias, SYMPLR BEE,         symplr_BEE, _color, _scale)
!define SYMPLR_BEE(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, SYMPLR BEE,         symplr_BEE, _color, _scale, _shape)
!define SYMPLR_BEE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, SYMPLR BEE, _label, symplr_BEE, _color, _scale, _shape)
skinparam folderBackgroundColor<<SYMPLR BEE>> White
