sprite $symplr_Desktop [64x64/16z] {
xTO5aaKX34JHnY7T-z_k-7otZ4jEoTDBYb8GGkfpEOs2ZKRvqHAULSf6TvgKuHaruPV9ydIJo0Iauf41B8tNXO0kdmKCpKrVPCrZQkprNHakjFVrzXFwwAEF
FlhegqRog9fxFPPyc3Tz8W7KuT4IC3NmX6o07rNnf8izdr7o6TL4l5WIpv3EVyXurSpTSoPSLsLm-1bzERF_YTjGftjLNBKvpnrRclxvf7i-il6aWHycX7i
}

!define SYMPLR_DESKTOP(_color)                                 SPRITE_PUT(                                  symplr_Desktop, _color)
!define SYMPLR_DESKTOP(_color, _scale)                         SPRITE_PUT(                                  symplr_Desktop, _color, _scale)
!define SYMPLR_DESKTOP(_color, _scale, _alias)                 SPRITE_ENT(  _alias, SYMPLR DESKTOP,         symplr_Desktop, _color, _scale)
!define SYMPLR_DESKTOP(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, SYMPLR DESKTOP,         symplr_Desktop, _color, _scale, _shape)
!define SYMPLR_DESKTOP(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, SYMPLR DESKTOP, _label, symplr_Desktop, _color, _scale, _shape)
skinparam folderBackgroundColor<<SYMPLR DESKTOP>> White
