sprite $symplr_Desktop [64x64/16z] {
xSzLjWKW34FHO2qayn_lTVS-5_Plra4mJSbwb1SSD4fnOvzNYTPYhFDm0EM8orJ1MY8Ja4h4Aa2NxNl05DFNYH_wej4YN0PJF_HD6I4SPxs5U_w0VlQpd_ti
Pr_bAQAgd_KO2ihdFQfvG4k0ox51LSGTCnCjtr7k3XInqoNnfhi39MRirS5eJqzuheW8-F2-lgKlT_xlU0rrivSgNf6eX1kwF7p_IlX-PDvc-66cQGa
}

!define SYMPLR_DESKTOP(_color)                                 SPRITE_PUT(                                  symplr_Desktop, _color)
!define SYMPLR_DESKTOP(_color, _scale)                         SPRITE_PUT(                                  symplr_Desktop, _color, _scale)
!define SYMPLR_DESKTOP(_color, _scale, _alias)                 SPRITE_ENT(  _alias, SYMPLR DESKTOP,         symplr_Desktop, _color, _scale)
!define SYMPLR_DESKTOP(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, SYMPLR DESKTOP,         symplr_Desktop, _color, _scale, _shape)
!define SYMPLR_DESKTOP(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, SYMPLR DESKTOP, _label, symplr_Desktop, _color, _scale, _shape)
skinparam folderBackgroundColor<<SYMPLR DESKTOP>> White
