sprite $symplr_EHRIntegration [64x64/16z] {
rTS7ZiCu34RXdwgK-Ev_tIsEO2-KJE1a-mSCgfw7egVgVoNtNlGz1vYcBpNeBN1zPb1bk0HLIl0Fzz_FlnjhVryhtQi-LIFfpsXatPLCpqmtLI2olbKXu6dQ
xAPRWYOvuKlIeLFsjz2BdXcOL3cv3hOTdW13pmAtD9ZrC5Q_Sw9tw7gIEPWE5PSicJQGfKBeMPumaWxcHF0GBT_fBzOccr6k-TsXwKVP0UQeZ-6jLW-0Rk_t
jpHWrktUgGLGrcOe-jbOEzYLkPPkeBTzqKljnpubNOAgfO_VrAlt_BkozIM0UlKqBJF6YA5bSjg_R0Agba4z2vVcsG-O3rsw35ngu4lGjdwx_sQI9OEBQzqz
_767KT_qpaZcHAiFut4iZcuzPxpfBG38MYhZw5sdCLRVoCeqAOPEQS0ySsNYJP-s_fd1qSynHf7QEN-dwmv8aloF-skFHLNTCMWltr-GTKTZlkeBw9O4jlfm
FpSrwRhbEkdpDqs73gPx2XHj2bJT5KyFgD1rMuhjipLmVS0c3DEI9ZHzf7Q8UcwEykRe9FhJjZnDeCaQroYN7inwFXscbgKbgG81uDfD09ga1DLoq2ILB9Lq
V7X-R0tcnEl6YMmLJ2fCIPEG39IOoenE77qlMSuBuuYAb23B0fVKgjIArBFD-kWb9NyocQQylayX84oRrRzaSKH-Bd0aVT8h3Q3hmR99z_ltqTv_u_i-DQ_s
Gvzxhtgl0KH-sJj0cDx8u6rUXpfNNw6tOEYDZak2IqzqQKufQ9A1VTJNgwUl_lRyo_tvLTV-llxdCRNUJ9lj_Vsd_0e
}

!define SYMPLR_EHRINTEGRATION(_color)                                 SPRITE_PUT(                                         symplr_EHRIntegration, _color)
!define SYMPLR_EHRINTEGRATION(_color, _scale)                         SPRITE_PUT(                                         symplr_EHRIntegration, _color, _scale)
!define SYMPLR_EHRINTEGRATION(_color, _scale, _alias)                 SPRITE_ENT(  _alias, SYMPLR EHRINTEGRATION,         symplr_EHRIntegration, _color, _scale)
!define SYMPLR_EHRINTEGRATION(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, SYMPLR EHRINTEGRATION,         symplr_EHRIntegration, _color, _scale, _shape)
!define SYMPLR_EHRINTEGRATION(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, SYMPLR EHRINTEGRATION, _label, symplr_EHRIntegration, _color, _scale, _shape)
skinparam folderBackgroundColor<<SYMPLR EHRINTEGRATION>> White
