sprite $symplr_ERP [64x64/16z] {
xPU7Tjmw30Kl2LPW_lztKyIpaI9pOpdll5CpzdQE05vrVSO_SfiUCKTD-WkAyukPzKNI16QrRAKvqFKbBA0bQP47UD9pCdY-BI-IdfA2kVlgAHFNYRMwMchw
1AkrPCdWqdo7e_S2wO_ov22wqrTTfQ8Cmnb7Lrtl6K3CCGDOXQ1qwY1aXBIUtv0SHdxrCLRZBXkfG1ahky3q1YVEt_8jJ5ZYU9jWtwxTf8CsXwqt36t9x3gR
zxmByrtvkVlMF_YkBK6HL8EPz0SgOTgGuFWLY4_sYbs2rW_DQJa8_qbRkQMpj7kLqk13XDc1UVYcOE4hltm61FJLPBlD2KPDQun3CREwV9tbeLPOuyc_woDf
CU78KOPl0eAqHerh8lJB9qkIzJw8_WEFdhK88eYNSlOrcPkCJrv33S1qu9JBu7pp6zxQ7Eq7quFoSMG_MwvCtVthX2RrJF2KXXRd3cNvZTzBMLpzULk-1NZQ
-C65JOLLVwKxyq6_-axuYtuMFQHpXpRY6hjlvtzo9dcOAziASG3pptwx5eXZm0Hes_at6KqffZGZhM951-VMd0RHzDQlKeoV_kOqD0bxiFxVdmOTXZtqRNSQ
7W2-c4cL8DpZU41Hdhu8zfS1UV0BKmekk5JuHVIiBTdAWQtJNYaLIedLlPM59JqcWUIO_eQM_vDV65_qKx4dzQsaDmNlgtNd9mVAFYiFffJJEdNNzFAhdKp2
8UtAkmeeuSfCDVpb_ux9TmqOOGsasPHcbT6Nt_mAD8jjeWvGFyp_HWLmRKWZlEepNzLZ93rX-Ll-Lz-cztJpq_2H7-e0VlC38Ei9Ws61pv-0L8VK2PiCFS4f
Sbv8JjPagZBrX4uCQFKdhKZ9f08ZQ7h4xZvd05CFAJNhZjMYZ_pZEm
}

!define SYMPLR_ERP(_color)                                 SPRITE_PUT(                              symplr_ERP, _color)
!define SYMPLR_ERP(_color, _scale)                         SPRITE_PUT(                              symplr_ERP, _color, _scale)
!define SYMPLR_ERP(_color, _scale, _alias)                 SPRITE_ENT(  _alias, SYMPLR ERP,         symplr_ERP, _color, _scale)
!define SYMPLR_ERP(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, SYMPLR ERP,         symplr_ERP, _color, _scale, _shape)
!define SYMPLR_ERP(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, SYMPLR ERP, _label, symplr_ERP, _color, _scale, _shape)
skinparam folderBackgroundColor<<SYMPLR ERP>> White
