sprite $symplr_Gear_Hub [64x64/16z] {
pLU9hYGX21HH4Uh__tTZ3oPDqXbdXprUlLE7qlBYA3yQVThiNxF9i63q9TzWdJjWdnWtaKvHFB0w2EXHLXTf9Q9UKgFXzER0ZCCkM0r30YP3WVkuwgq6ZNGT
OW25gNGr1n0wnyFyk7f98Q7p9SVk0jfhZehGwRl9G90VbknGOBI1A7-B0UZEfx1axrOiA0M-nYcT9owAug4QB1uL0Rp-Ib35W73jW9I8WL4Y1EYLfmyJ3nLQ
ZloYyAiIi4RKNaZRMtvNAbrXivP7CEGjNuBi1zJGK00pTfK3xaiGBCXT_16-XCjICNZTNc_FBVwu13BqGWFWma2dTMteA3w-PWMkEmR_t-Wt_9RrnUgBGdsn
ktu-W2pJAbmsMEeQT7p8RtZOA0wT9m7OhBP91dcpOcQA0gvUFtzQZU158e6ccsqeXhj_c-OxFw2HW7aHtCxD5gexBdqvMRQBIK2hZuHvsR4laFmTk_jpvdwt
vEV3roMP_d6zEPy6wApR_TuSS9tktxSBgYy2x_W4nzmRpixdlVJf5dQp-8QFcqLI_-VxDn_sxtH-V3Y_y_tHn_iZVdy-kx_bS7yJxoVnVl-U_o239lnNmdy-
--znyD-9-96EN-VugS_nCns_C_a39aVwoEKlBP4_9VAtLFwOpr_J-NC-Vy_N3_dwvLm_jQVwwGm3l7vBre_9-lKdunS
}

!define SYMPLR_GEAR_HUB(_color)                                 SPRITE_PUT(                                   symplr_Gear_Hub, _color)
!define SYMPLR_GEAR_HUB(_color, _scale)                         SPRITE_PUT(                                   symplr_Gear_Hub, _color, _scale)
!define SYMPLR_GEAR_HUB(_color, _scale, _alias)                 SPRITE_ENT(  _alias, SYMPLR GEAR_HUB,         symplr_Gear_Hub, _color, _scale)
!define SYMPLR_GEAR_HUB(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, SYMPLR GEAR_HUB,         symplr_Gear_Hub, _color, _scale, _shape)
!define SYMPLR_GEAR_HUB(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, SYMPLR GEAR_HUB, _label, symplr_Gear_Hub, _color, _scale, _shape)
skinparam folderBackgroundColor<<SYMPLR GEAR_HUB>> White
