sprite $symplr_Gear_Hub [64x64/16z] {
xPU7hkmg34Ljq-tz_z_x3c6CXOwYpBkzBRNi6HOz1Vgs_4Ccju7fWOf9Ms5WKbOmJEJ1xu01OmMzGbq1C0Foer-fX9-eXS-aFy2VR7-o_Kd-plD7qj1bXu7g
WSMGcHwfQ146IWI3q0_sE_9N-Lpe3RyuEVpWqS_OoFILzp-bbEqatFZS-eisaw4TcodlvWUzW_Iq3HswQwijYgGFU4UM5_kdKkSb85JHfr0J1OA9nS0sl3Uk
fdRb0cZ90CenOMgxC8avogxRrKBnIPYvX0ybSlyp3SXYqEHxm33cZ-bDVs1CpUEwPg24Fzc-g7tGoKdOSnueZE_cpwDJNq7gq55S4TfmyjPZ_IBJG8zd2IpD
O2WK28nkuTLM0qR9nTR4LUXxVXjw5Kq-OHssAXqzF_iLM6BVasZ8lW_anY_reX0rZ78DE0gtLTCSIYAkatRwWXToFkyNn_kWOk7-Nl59dOtrB6VxTIs7fAlz
jiYdRyVuyxM8CVuIuz_S-DHqFIYIR_ZcyszQwT5VHNars99aNTqfllvFVko_ZaK-zXyxztvvnTJDj5u5zuOlSEnSlH6rORL_OD3pOVtAKULn_mVHIA6Jy0SB
mcz0OetNS5Oqga2wzud3Z-UVvbdRklJlYAHE3n-gxkyFfzpz-Mkrm7MgSBQGFs_esfY8u_cV-XvySfYSb3yGJzmatbWztZ-bqZjm6CVt3ndwLVj4w9QAUD3w
Ezs7AJx-GJSyll-vJkHDdnFzqE-Vd__znWsTTnYe4Go9tZy_nFVFyVtxdR-_V_xvmTIsFqFufdZq6oRzzloGw84qeGL_2aA_6Fy1
}

!define SYMPLR_GEAR_HUB(_color)                                 SPRITE_PUT(                                   symplr_Gear_Hub, _color)
!define SYMPLR_GEAR_HUB(_color, _scale)                         SPRITE_PUT(                                   symplr_Gear_Hub, _color, _scale)
!define SYMPLR_GEAR_HUB(_color, _scale, _alias)                 SPRITE_ENT(  _alias, SYMPLR GEAR_HUB,         symplr_Gear_Hub, _color, _scale)
!define SYMPLR_GEAR_HUB(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, SYMPLR GEAR_HUB,         symplr_Gear_Hub, _color, _scale, _shape)
!define SYMPLR_GEAR_HUB(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, SYMPLR GEAR_HUB, _label, symplr_Gear_Hub, _color, _scale, _shape)
skinparam folderBackgroundColor<<SYMPLR GEAR_HUB>> White
