sprite $symplr_HealthHub [64x64/16z] {
rTU7Skig54RX7n3iijx_UKyX2fDHoSY-zNpfPMt9uAe_IXkswNqE44Llwc0ZyPUFsbKm2RfKuL_kbmvZ9Fwlhz_Ix8tzsxBghnWqFLMBpieB2qmslQiprUCv
MT4Zq2KZRLSr6TjXGMriEYjGfCvYcihXdmF0TPPOgK7qoJ5TCHW3XauQKz7KCQcKeWDeqaRgh0Nu7XHZoTuUzKlfmO5lw_pJ3OPkLGT8xxLy3EkM0ADyjtxB
0AANmyoHi6zadz_S2hpgUdNiSwFrZRYRFcxxKgKbwTfP_D9NZxVVjaFV4kXV-g5Tf7kwTiboSRLP0vnjzJu_TWxvmVI5Or87soNzkX-OBYHDAd2uuPZFSv-N
mVitlHEr6FHTCEROZ8XD6X6HyKrVc9fs7P-zQV7FVb3Lw5Awbk8GArSZ7_Lt2im-tRr9tTrpxuUUW3gF6V6nVX4nGwVhYQ1Vxb_Iz4Gdhle6UgH2sViqMoiL
33sp_jFpb_tx0KNFRB3T_EuPO3lbfiVgSS00rmjAWfSrBc3e9Ts0lWxEfbizIJkjbjUO4yfWdig19TdNT0XDowXIPsSw2duRaWhqqd9-tvgqrVbXzNDq1DuF
d6obGv7QF7J27ALAgX63dBsrAkE2VzuUAbILn2JrJHg_Frg9lkvmgfq4MTJssoaaPD71wc-sDy7rcm5HzKgl6h3-M6gH7lStqNt_klVxEgoNcxuDwu-UGRRB
tc1jquq6reCiftwz-0bzm-R_yuLLXfGX9MD_YdbldFhjfRw2Zo3Bko_UEa1M7JnQlxL_3rwy_d_y1
}

!define SYMPLR_HEALTHHUB(_color)                                 SPRITE_PUT(                                    symplr_HealthHub, _color)
!define SYMPLR_HEALTHHUB(_color, _scale)                         SPRITE_PUT(                                    symplr_HealthHub, _color, _scale)
!define SYMPLR_HEALTHHUB(_color, _scale, _alias)                 SPRITE_ENT(  _alias, SYMPLR HEALTHHUB,         symplr_HealthHub, _color, _scale)
!define SYMPLR_HEALTHHUB(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, SYMPLR HEALTHHUB,         symplr_HealthHub, _color, _scale, _shape)
!define SYMPLR_HEALTHHUB(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, SYMPLR HEALTHHUB, _label, symplr_HealthHub, _color, _scale, _shape)
skinparam folderBackgroundColor<<SYMPLR HEALTHHUB>> White
