sprite $symplr_HubCompliance [64x64/16z] {
vTU7Zgmy38RXLDlnU__N-vUWOS2GQT9HEz_syZWc5E-cloDLRVWmAR_WhEnn-PeBkDJyVw6cuEsxnGVUqpCTz1lksAMWVUu7acBiymuKlItQF-E54OzdleDF
TEs36hw5vxc9yjb9jyZP2ZZlEdTSZ1Pvqtb8IdtDeQSqkF0qqFcfllG-Ltxidig1RuV4UCNRB9_PVjT00q_uAs-KUH2wVM43FVAt6uYdv_fGy-38t_jn-51d
WPsl-g_ruEsmo2oGyeaNBF01deDNwbxWn5EddNd750c-8lkPF_4qoF56AmKBFZbvBt3azT9-0-ZHT_GX-lbWImeHa1Jzl0wl4JJjYMUq3KufAQRXQUaBkEDx
k7JGeQozqEB6o76li-5bSSkrcfB6uiLXdpjLOUHqxu4-_RLXt5JKU34-YeZqlFcOPiourlGckm_1QyahrBNT-2nIuYqvzq128GFauZD0lVW6U0vJee9lOVST
QTZkdx_Gb7xsbjcpBodqUlHxYj3ZlO_Uzz-U_j1_k7kpMB_Plp9vzAcPbhJCSUGDKlJhv3RZjALl_wMk5zvos1ix-mAist0kw-Toy6EkFyXB_oZpQYJOd_RX
sWW3O-qR6omiCjkgeBUyFd_5V0l0uxsFjXUNEw_KkvaMPbMdBoQ_e7fehTpxXdNipcS_tjKP3VvmaPN51hQStlhKUaxBlFFlqxMjV5LvomtGUzy1VzlsADli
E_lv7QhItlhi07Xx-kBCbEdVzc-t_wgyxtz6JCwNT3_CCCtfcmWrCzBFwPYYtxlu9-7lgJNzwVmB
}

!define SYMPLR_HUBCOMPLIANCE(_color)                                 SPRITE_PUT(                                        symplr_HubCompliance, _color)
!define SYMPLR_HUBCOMPLIANCE(_color, _scale)                         SPRITE_PUT(                                        symplr_HubCompliance, _color, _scale)
!define SYMPLR_HUBCOMPLIANCE(_color, _scale, _alias)                 SPRITE_ENT(  _alias, SYMPLR HUBCOMPLIANCE,         symplr_HubCompliance, _color, _scale)
!define SYMPLR_HUBCOMPLIANCE(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, SYMPLR HUBCOMPLIANCE,         symplr_HubCompliance, _color, _scale, _shape)
!define SYMPLR_HUBCOMPLIANCE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, SYMPLR HUBCOMPLIANCE, _label, symplr_HubCompliance, _color, _scale, _shape)
skinparam folderBackgroundColor<<SYMPLR HUBCOMPLIANCE>> White
