sprite $symplr_MobileHealth [64x64/16z] {
tTO5bjqm40NH9rPtxN-_EOOP3ScMmqbzXcic_JU5MKlOcDTrM-EgghkWnbaDN_1PHwL4nRBr-iqZ3rM5lU_oxaNPj-oXdxJetMOvBFYBbhorMGQ_OVw7ptcy
FFUfGv0KeSNtFZLtR-dI9tZr48SVkvY52syum_VXWuFNKXq8S-_KKhHLSyE6zvU_PF1BhvU6trLIRDwZ4kJ7tkYAR4LrxB67BCUhuyhmr0U8WgG4YX1ctkYI
nllJxnQgwesla7IKeGnFLMEhgLnCVm2mLfi1wDKta3hG9MXJhyQe3Xzs6LAGEeIvLmK_ZXf5mwk0Pqdf_67grQ0TJs-zwll9cdjri1S-lAAnPKatNWPqlVTR
mR0WtNevfY-yEbrhldxmCJpn7SzRKP9Ypj71mxfFd3NjiUNhNiauIkVWOeQmw4TsJ4012T9J7_ofJyxxuYCV-53M8r_n5D-aeugl-ORfSn7Qci_WdmF2cbVd
ow8MlLBzLEj5AtvMmN-3lxZ-NF7N_HoVPRIPBs5MnSzLwv2-U_a51vhkVMVBt_kjN98MlB7ttTT_AUz9l_NwksXMNV2Tgvhk2iuy2xelfbbH_t7V
}

!define SYMPLR_MOBILEHEALTH(_color)                                 SPRITE_PUT(                                       symplr_MobileHealth, _color)
!define SYMPLR_MOBILEHEALTH(_color, _scale)                         SPRITE_PUT(                                       symplr_MobileHealth, _color, _scale)
!define SYMPLR_MOBILEHEALTH(_color, _scale, _alias)                 SPRITE_ENT(  _alias, SYMPLR MOBILEHEALTH,         symplr_MobileHealth, _color, _scale)
!define SYMPLR_MOBILEHEALTH(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, SYMPLR MOBILEHEALTH,         symplr_MobileHealth, _color, _scale, _shape)
!define SYMPLR_MOBILEHEALTH(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, SYMPLR MOBILEHEALTH, _label, symplr_MobileHealth, _color, _scale, _shape)
skinparam folderBackgroundColor<<SYMPLR MOBILEHEALTH>> White
