sprite $symplr_Orchestration [64x64/16z] {
rLPdOZ0h27nOK6JkVzuNdHI-pR8f_p8fMuG5XgB__I7yVPIvrgo_LbSSZ5-gDy1Qcu3-JjzfkGE_2_vDp_50GLLjoGgSDuQMQSi20BzT5q2-i2yEs7JS6rYO
-pBWjyfSAhb41Lox0Jrdk8NhpVA1fj43l9ctCWeCCoqv-MyCsPsBGiUVi32OQTmOCTZN5OfHfE5EiWCIk9Ga0OJBi_S2B_SUBC27OttsVlqRgKkMXHS279Cr
hxQMZROZAvTAUsAZdYul1X3-AUi5QCzCQWTWlTOs796yQkLKWtyvQwPyyBeaLBc48arW9BoDeUKmOg59zxs6DrrxkR1uAEmi-NdYxI7sodwEMHyN_zS9meSQ
zdrdlC86jPD3Vd42QnemhwrOGTQPJewDzM5wq6Hb9XelSTWPw1CRWkBprD7Qifq431gcKo9RV7zjVRGZ6vBYD3tHj-4LcfLpsR4NwykVqmTYO52SOT2NGaQC
GPAWCLzicnpw9EehNTfE5Jvp89FfZHLAbCOSBR2fcAI9FZD6PdfLgHPAb66oqDv6BdKuOkX4nwGj485-SYz-je8ozrhXzzME4_un9Ic0MQ8w6xOuYBu_EEES
8vEXwQ-mqp7g0AoSKYoXjuJqFK2S6Y8VtKHKtizGyTai7BJPulnWybcJ6RY-0BZPkMZa9ko6ANQJLyF1KbOr4JZ8CS7SrzPhOKA22-os35olbtXMK13avCcs
wBIMmaPEEqE-MLBZzGa6k2MRl96o9tJoOlVi2YUWF6LDUKts-ZuTmAg9EXkJDPQa1N3ax3lgapuRMWRGC_gevxS22fTmcBW1HtunU7e-o_cXuqJDpbU4fWnq
JepqV4TesdrCy7DsEFj-ZWaB6zhFKS2mgzFz7wC3FeVnDF8RjBS3nQzHLNim_iVnFm
}

!define SYMPLR_ORCHESTRATION(_color)                                 SPRITE_PUT(                                        symplr_Orchestration, _color)
!define SYMPLR_ORCHESTRATION(_color, _scale)                         SPRITE_PUT(                                        symplr_Orchestration, _color, _scale)
!define SYMPLR_ORCHESTRATION(_color, _scale, _alias)                 SPRITE_ENT(  _alias, SYMPLR ORCHESTRATION,         symplr_Orchestration, _color, _scale)
!define SYMPLR_ORCHESTRATION(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, SYMPLR ORCHESTRATION,         symplr_Orchestration, _color, _scale, _shape)
!define SYMPLR_ORCHESTRATION(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, SYMPLR ORCHESTRATION, _label, symplr_Orchestration, _color, _scale, _shape)
skinparam folderBackgroundColor<<SYMPLR ORCHESTRATION>> White
