sprite $symplr_SUID [64x64/16z] {
pPS5Zgiz34Mlmt3slzqVNZzvAAgV8feZ66XZIdBjw3TZVQrkkYLjW9rqoMALibYtxi4aWxi0ocPB4fIRqWs0B6MmA-Vq0Rt3KBfmlh9i0InB32d6Slxa_FLR
xqMoMHKpW5tS-O5e-TgGtVaNohHmiuiqs6VdWo2YodnPeP_jArg_dlN3T2I_DM5GPPCDk-g01VUW0q1A2ux5wi4cjWqhIMhd46BIuzP3i3PdarF8Kfqpa1GF
mJR0DgynHHCWsimdXCMkTJE_LgdLnLP80qXIWj6TbnXiYaBoen-RBvYaIOsNqtdyz-P0bMoJ5P5sdUpMFkTlQj3Z_DM69DSF_ozF_NSAJlX-DA-EKUMKdQGo
HZCTwC3EaefaIG6dvHl8gZIT63NMZycKzNHn_rm_Sd0xxlJ7t6mG_uPzeNzUlvGtXtPHXYd0zwzx227dy_E4uEV7LfFZvoTAvjp_PZoIU0X-VznVV7-S3gVx
--X7LaZbvOQZVbpfrm3NhrW_n_okdvFj-dcXtnsIwtVGFrxdxKl_o53Uz8_6-_vbc_wN_VDus2VhidzxyfVpWoSVwuT_wvnyF3yjrxz3yk7yvlfxJZxMZoAf
cioEoSVpwyF2V7uz91_Iv-V-TqW-9gtopE_hJV9n_yz0qGMMUUQFeIiiU3zTlT_ktu_txzVVpBy
}

!define SYMPLR_SUID(_color)                                 SPRITE_PUT(                               symplr_SUID, _color)
!define SYMPLR_SUID(_color, _scale)                         SPRITE_PUT(                               symplr_SUID, _color, _scale)
!define SYMPLR_SUID(_color, _scale, _alias)                 SPRITE_ENT(  _alias, SYMPLR SUID,         symplr_SUID, _color, _scale)
!define SYMPLR_SUID(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, SYMPLR SUID,         symplr_SUID, _color, _scale, _shape)
!define SYMPLR_SUID(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, SYMPLR SUID, _label, symplr_SUID, _color, _scale, _shape)
skinparam folderBackgroundColor<<SYMPLR SUID>> White
