sprite $symplr_SymplrLogo [192x72/16z] {
xPg7Zkiu34L9YQha_t_lnjczYCBXAn5UiO0zQ3Ckz8b4MWMc057hJ37DjDAzIVQWKqYr1qAtfjX5eWYr1urkJRQBIW62KxTcsWEbW64NJFUcseL4bO7Ik3Li
5oDw-LnakZizhc1MUp09tBo2M_nYAWHkNi4px1PbkZybhDEANha_mqmJENYQJQOZo9d3etG3RWvVqB4az_AEoNtqKOxrbvwOgVH3_NdGL9sfb3FzYz2iF2kD
C_rReZc7PXgKg_1n_ZNJR6CGpM9csj9X_hdHB4abDxKdGuxofouvKPR11hJoGVxKckGw4dK3qSIUfOsfEcSlYIuuN_WdvWU9dd3fKrLd4wBro1mjX-5nAl37
DS-0tPLfafBfGLC3sOT_dWCZ4vOm4iosArrKDQ3oRuobWOHMUBbubi3V1wmKmULwVg2LLtiejgyzbV50uk6lzqU-7NwcmD_TFfX2Sdz6S1savYbXTWui5cXy
kRv_EGAAELISVn1mq3VWEbeAii96oIdbEWrhh-4NCGbzHnLFwVs_wvjTwEXT3H4MVKVs_jKyTNSNgw7v11gW8gD8xQBpqsAuDXTT5zKP9qUj5PSgh_ueDfib
SIfemOysWTHrHySVXG0h_fVttQ7nLbNmceZsf35TS3VSk_hBMyxqptOFciktfW_wgxt1gpyQ7hpw8iHw7jcZsLT3Nlnn0xyrLF_8Nzsow1Kdk-f5cmvVGE8B
9Jg5LE-hlm_OFzfzAdZfnx-iG-fLUOg2yUqDK57XFkH4Fy8V0T-Dz9DX_6BsAedT6HJIEXwmpy_g2kxbKuBXKd3C-xihw9C40ZfxOG83ealrmb-yls_Y5kJc
-lEzVo6GoWLz_0D0Jsj3pBLFG_yI-yUPZDOE_BV9mzw172eOIhVp1wdqgVOYBPdHNrEV3V-D_Dc4arGC_sDz5XDr7DpmjnJLxw_s1w9m9WXKA6_wDrePttX_
bb-qYoS8-tg5OYZUy4Sm5txGh_BtDoFisbg2ajlqdyal1kJN-VlPG47-BBCUTFcclwdWKiNaxbVv-npDklmUnBxejECFPfKi3S7ojdzgiwTW_c_Q96UfmvnT
XK7Uz_SKslGN5ByRVZsTtBGVrVjB_2jj-NCDrk_X3sW4NWxbL_chq8u_zs3_99m_Z1pab_As_qXh-CuK-zSVbYaOqVoXZVbWj99--2bAkk1ruBw8Bi2mdUgy
ekYeNouB0eQiEqWVWQdFvxXf1mptK7lIyxR3ll-lGFQsRf7jVzsVKjcHmEBgh_hlWtV3iVvY5togFtPz3lN7hi-f_XYQTf7wGEZR_4yMfcF1zql7Kb1WPuBl
zqu5tq-U2lR73YNPsUcFxxTFHJ4tFXF1RiQXOAVmL99YRdmeUMfdEeD_
}

!define SYMPLR_SYMPLRLOGO(_color)                                 SPRITE_PUT(                                     symplr_SymplrLogo, _color)
!define SYMPLR_SYMPLRLOGO(_color, _scale)                         SPRITE_PUT(                                     symplr_SymplrLogo, _color, _scale)
!define SYMPLR_SYMPLRLOGO(_color, _scale, _alias)                 SPRITE_ENT(  _alias, SYMPLR SYMPLRLOGO,         symplr_SymplrLogo, _color, _scale)
!define SYMPLR_SYMPLRLOGO(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, SYMPLR SYMPLRLOGO,         symplr_SymplrLogo, _color, _scale, _shape)
!define SYMPLR_SYMPLRLOGO(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, SYMPLR SYMPLRLOGO, _label, symplr_SymplrLogo, _color, _scale, _shape)
skinparam folderBackgroundColor<<SYMPLR SYMPLRLOGO>> White
